# Generated by Django 2.2.3 on 2019-07-20 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('room', models.PositiveIntegerField()),
                ('status', models.TextField(default='Не выполнено')),
                ('author', models.ForeignKey(on_delete='models.CASCAD', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
